### ISSUE TITLE
Question: How to bind to form?

### ISSUE THREAD

**Issue by mmoyles87** [sfxcode/sapphire-core#1]
I saw in the description that you could bind to a form. I see in this example [IssueTrackingLiteController.scala](https://github.com/sfxcode/sapphire-demo/blob/master/issues/src/main/scala/com/sfxcode/sapphire/core/demo/issues/controller/IssueTrackingLiteController.scala) you are binding to ui.detailPane. Could that be used to then get a bunch of child elements?

**Comment by sfxcode** [comment]
The binding is done by the FXBeanAdapter. The ui.detailPane is used for lookup of elements to bind. The detail pane is the root node for this lookup. After that you can bind any sub elements with an identifier.

Example can be found in the sapphire [extension demo](https://github.com/sfxcode/sapphire-extension-demo/blob/master/src/main/scala/com/sfxcode/sapphire/extension/demo/controller/form/FormController.scala).
This project is work in progress, but can be used as blueprint for a sapphire-core application.

Greetings,

Tom
